name: Reusable workflow example

on:
  workflow_call:
  
jobs:
  display-variables:
    name: MyName
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    environment: Dev
    steps:
    - name: Use variables
      env:
        REPOSITORY_VAR: ${{ vars.MYVAR }}
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository variable : ${{ vars.DEPLOYMENT_ROLE }}"
