name: Build Image

on:
  workflow_call:
  
jobs:
  cdk_build:
    name: cdktf Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"
          terraform_wrapper: false

    - name: Create File
      env:
        REPOSITORY_VAR: ${{ vars.MYVAR }}
      run: |
        echo "repository variable : $REPOSITORY_VAR" > myfile.txt
