name: Build Image

on:
  workflow_call:
  
jobs:
  cdk_build:
    name: cdktf Build
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"
          terraform_wrapper: false

      - name: Create File
        env:
          REPOSITORY_VAR: ${{ vars.MYVAR }}
        run: |
          echo "repository variable : $REPOSITORY_VAR" > myfile.txt
