name: "MyDeploymentWorkflow"
run-name: "Deploy AWS Network Firewall - EU-WEST-1 by @${{ github.actor }}"
on:
  workflow_dispatch:

env:
  DEPLOYMENT_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/lab' && 'lab' || 'lab' }}
  STACK_PATH: "test"
  STACK_NAME: "${{ inputs.Spoke-VPC }}"
  REGION: "${{ inputs.Region }}"
jobs:
  Build-Deployment:
    name: My Deployment
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - region: "IDN-EUW1"
            stack: "site-a"
          - region: "IDN-APSE2"
            stack: "site-b"
  prJob:    
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
    
