on:
  workflow_dispatch:

jobs:
  display-variables:
    name: My Workflow
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    environment: Dev
    steps:
    - name: Use variables
      env:
        REPOSITORY_VAR: ${{ vars.MYVAR }}
      uses: ./.github/workflows/mynestedworkflow.yml
    - name: Use variables
      env:
        REPOSITORY_VAR: ${{ vars.MYVAR }}
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository variable : ${{ vars.DEPLOYMENT_ROLE }}"
        cat myfile.txt
