on:
  workflow_dispatch:

jobs:
  display-variables:
    name: My Workflow
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    environment: Dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 0
    - name: foo
      uses: ./.github/actions/build@v1  

    - name: Use variables
      env:
        REPOSITORY_VAR: ${{ vars.MYVAR }}
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository variable : ${{ vars.DEPLOYMENT_ROLE }}"
        cat myfile.txt
