name: "MyDeploymentWorkflow"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/myworkflow.yml'
      - 'test/**'
jobs:
  Dev-Deployment:
    name: My Dev Deployment
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    environment: Dev
    env:
      STACK_PATH: "test"
      STACK_NAME: "MyTestStack"
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 0

    - name: Install Dependancies
      uses: ./.github/actions/build 

    - name: Show Variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository variable : ${{ vars.DEPLOYMENT_ROLE }}"
        cat myfile.txt
        echo "${{ vars.BUILD_ROLE }}"
        echo "${{ vars.DEPLOYMENT_ROLE }}"
        echo "${{ vars.TARGET_ACCOUNT }}"
        echo "${{ vars.STACK_PATH }}"
        echo "${{ vars.TF_BUCKET_NAME }}"
        echo "${{ vars.TF_DDB_REGION }}"
        echo "${{ vars.TF_STAGE }}"

    - name: cdktf synth
      working-directory: ${{ env.STACK_PATH }}
      run: cdktf synth



  Prod-Deployment:
    name: My Prod Deployment
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    environment: Prod
    needs: Dev-Deployment
    env:
      STACK_PATH: "test"
      STACK_NAME: "MyTestStack"
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 0

    - name: Install Dependancies
      uses: ./.github/actions/build 

    - name: Show Variables
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository variable : ${{ vars.DEPLOYMENT_ROLE }}"
        cat myfile.txt
        echo "${{ vars.BUILD_ROLE }}"
        echo "${{ vars.DEPLOYMENT_ROLE }}"
        echo "${{ vars.TARGET_ACCOUNT }}"
        echo "${{ vars.STACK_PATH }}"
        echo "${{ vars.TF_BUCKET_NAME }}"
        echo "${{ vars.TF_DDB_REGION }}"
        echo "${{ vars.TF_STAGE }}"

    - name: cdktf synth
      working-directory: ${{ env.STACK_PATH }}
      run: cdktf synth
