on:
  workflow_dispatch:

jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/mynestedworkflow.yml

  display-variables:
    name: My Workflow
    needs: call-workflow-2-in-local-repo
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-22.04
    environment: Dev
    steps:
    - name: Use variables
      env:
        REPOSITORY_VAR: ${{ vars.MYVAR }}
      run: |
        echo "repository variable : $REPOSITORY_VAR"
        echo "repository variable : ${{ vars.DEPLOYMENT_ROLE }}"
        terraform -v
