on:
  workflow_dispatch:
    inputs:
      Spoke-VPC:
        type: choice
        description: Dev Spoke VPC
        options: 
        - all
        - mydev_vpc1
        - mydev_vpc2
        - mydev_vpc3
        - mydev_vpc4
        - mydev_vpc5
        - mydev_vpc6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product: ${{ fromList(github.event.inputs.Spoke-VPC)}}
    steps:
    - name: Hold
      run: |
        echo "Hold"
