on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        ref: refs/tags/v1.0.3
        path: v103
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        ref: refs/tags/v1.0.4
        path: v104

    - name: Read File in v1.0.3
      run: |
        cat v103/README.md

    - name: Read File in v1.0.4
      run: |
        cat v104/README.md
