on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        ref: refs/tags/v1.0.0
        path: v1
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        ref: refs/tags/v1.0.1
        path: v11

    - name: Read File in v1 
      run: |
        cat v1/README.md

    - name: Read File in v1.0.1
      run: |
        cat v11/README.md
